before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: WwoG5Kb6FA2pZWO30zjqbHTajB9R6f1u7BuQOexN4Rwa4lRvbfz4WSApAJkuWPw/nskkedBPaKXKvMsSxOsFvKQEnaSbJRl/cJSeBTHGJxEgMtinnAMPJzGS8kDzK6abep9oz0k/oGXjEWkJ+NgwBin58OEMpyJRXXfNvqvJnkIhymPv3W2YXjuWZ6iN/bjaJJZ1tmJnwxAKAa9wvdZUobJqmGm9OjXV/CckTsdmTk37Lq2ctGICEVtftjsoooinl/M/gNuBX14K1FnZ+SQIiLVep1Lhet1VV4gkS1eK9BO8A3D1yv1ceVV6j+34m/XVqGzRI92Wf9pgpLeafqrc6bHq/rZu5K2kXqavHqSB6gByWTaDjx418w7T3BvAO+eJDyCIfPIievJmUMQj36wnMsnY/HesfQfEH+R/4WAxfc6llh3IJtTAey9SEMahNv7SSH5IyDqzuBozBrWPtxyWN/oAZkPG2HUuKU65+5oVWpGJqiZWddYPhXrc7OkWR9LdZ7tmvA4F7j9D+Y93AxcvpwAr79Nhbw+TSEhRtQYdoDZ4QLptp1+0WRtvJbjWf8VT2VNcqyIHmfYqpTsZTzUPjkm94dXsxXuMKvunmR9caSIADpLLwx12KN5uECPEH+0NEv9kukEbiNYh6qLxJVAev9Vz6Ui7JqnBWzwOZMvMegg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
